# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle # workflow의 이름

on: # 어떤 Events를 가지고 실행할것인가
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs: # 하나의 workflow는 여러개의 job을 가질 수 있다.
  build:

    runs-on: ubuntu-latest

    steps:  # job은 여러개의 step으로 구성되어 있다.
      - uses: actions/checkout@v3 # 다른 사람이 정의해둔 action을 사용해서 쓸 수 있다.
#      - name: Set up JDK 11
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # shell command을 실행할 수 있따.
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#        with:
#          arguments: build


